// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/fulcrum.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgregarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector   string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base     string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Enemigos int32  `protobuf:"varint,3,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
}

func (x *AgregarBaseRequest) Reset() {
	*x = AgregarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgregarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarBaseRequest) ProtoMessage() {}

func (x *AgregarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarBaseRequest.ProtoReflect.Descriptor instead.
func (*AgregarBaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{0}
}

func (x *AgregarBaseRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *AgregarBaseRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *AgregarBaseRequest) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

type AgregarBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *AgregarBaseResponse) Reset() {
	*x = AgregarBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgregarBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarBaseResponse) ProtoMessage() {}

func (x *AgregarBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarBaseResponse.ProtoReflect.Descriptor instead.
func (*AgregarBaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{1}
}

func (x *AgregarBaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type RenombrarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector      string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	BaseAntigua string `protobuf:"bytes,2,opt,name=base_antigua,json=baseAntigua,proto3" json:"base_antigua,omitempty"`
	BaseNueva   string `protobuf:"bytes,3,opt,name=base_nueva,json=baseNueva,proto3" json:"base_nueva,omitempty"`
}

func (x *RenombrarBaseRequest) Reset() {
	*x = RenombrarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenombrarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenombrarBaseRequest) ProtoMessage() {}

func (x *RenombrarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenombrarBaseRequest.ProtoReflect.Descriptor instead.
func (*RenombrarBaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{2}
}

func (x *RenombrarBaseRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *RenombrarBaseRequest) GetBaseAntigua() string {
	if x != nil {
		return x.BaseAntigua
	}
	return ""
}

func (x *RenombrarBaseRequest) GetBaseNueva() string {
	if x != nil {
		return x.BaseNueva
	}
	return ""
}

type RenombrarBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *RenombrarBaseResponse) Reset() {
	*x = RenombrarBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenombrarBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenombrarBaseResponse) ProtoMessage() {}

func (x *RenombrarBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenombrarBaseResponse.ProtoReflect.Descriptor instead.
func (*RenombrarBaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{3}
}

func (x *RenombrarBaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ActualizarValorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector   string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base     string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Enemigos int32  `protobuf:"varint,3,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
}

func (x *ActualizarValorRequest) Reset() {
	*x = ActualizarValorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizarValorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarValorRequest) ProtoMessage() {}

func (x *ActualizarValorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarValorRequest.ProtoReflect.Descriptor instead.
func (*ActualizarValorRequest) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{4}
}

func (x *ActualizarValorRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *ActualizarValorRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *ActualizarValorRequest) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

type ActualizarValorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *ActualizarValorResponse) Reset() {
	*x = ActualizarValorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActualizarValorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarValorResponse) ProtoMessage() {}

func (x *ActualizarValorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarValorResponse.ProtoReflect.Descriptor instead.
func (*ActualizarValorResponse) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{5}
}

func (x *ActualizarValorResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type BorrarBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *BorrarBaseRequest) Reset() {
	*x = BorrarBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrarBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrarBaseRequest) ProtoMessage() {}

func (x *BorrarBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrarBaseRequest.ProtoReflect.Descriptor instead.
func (*BorrarBaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{6}
}

func (x *BorrarBaseRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *BorrarBaseRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type BorrarBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *BorrarBaseResponse) Reset() {
	*x = BorrarBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrarBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrarBaseResponse) ProtoMessage() {}

func (x *BorrarBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrarBaseResponse.ProtoReflect.Descriptor instead.
func (*BorrarBaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{7}
}

func (x *BorrarBaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type GetEnemigosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sector string `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	Base   string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *GetEnemigosRequest) Reset() {
	*x = GetEnemigosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnemigosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemigosRequest) ProtoMessage() {}

func (x *GetEnemigosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemigosRequest.ProtoReflect.Descriptor instead.
func (*GetEnemigosRequest) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{8}
}

func (x *GetEnemigosRequest) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *GetEnemigosRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type GetEnemigosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemigos int32 `protobuf:"varint,1,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
}

func (x *GetEnemigosResponse) Reset() {
	*x = GetEnemigosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fulcrum_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnemigosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemigosResponse) ProtoMessage() {}

func (x *GetEnemigosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fulcrum_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemigosResponse.ProtoReflect.Descriptor instead.
func (*GetEnemigosResponse) Descriptor() ([]byte, []int) {
	return file_proto_fulcrum_proto_rawDescGZIP(), []int{9}
}

func (x *GetEnemigosResponse) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

var File_proto_fulcrum_proto protoreflect.FileDescriptor

var file_proto_fulcrum_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x22, 0x5c,
	0x0a, 0x12, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x22, 0x2f, 0x0a, 0x13,
	0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x70, 0x0a,
	0x14, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x6e, 0x74, 0x69, 0x67, 0x75, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x41, 0x6e, 0x74, 0x69, 0x67, 0x75, 0x61,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x65, 0x76, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x4e, 0x75, 0x65, 0x76, 0x61, 0x22,
	0x31, 0x0a, 0x15, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x60, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72,
	0x56, 0x61, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x65, 0x6d,
	0x69, 0x67, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x65, 0x6d,
	0x69, 0x67, 0x6f, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x42, 0x6f, 0x72,
	0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x42, 0x6f,
	0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22, 0x40, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x32,
	0x8a, 0x03, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x48, 0x0a, 0x0b, 0x41,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x75, 0x6c,
	0x63, 0x72, 0x75, 0x6d, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75,
	0x6d, 0x2e, 0x41, 0x67, 0x72, 0x65, 0x67, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d,
	0x2e, 0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e,
	0x52, 0x65, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72,
	0x75, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61, 0x6c,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x56, 0x61,
	0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x42,
	0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x2e, 0x66, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e,
	0x42, 0x6f, 0x72, 0x72, 0x61, 0x72, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f,
	0x73, 0x12, 0x1b, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x69, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fulcrum_proto_rawDescOnce sync.Once
	file_proto_fulcrum_proto_rawDescData = file_proto_fulcrum_proto_rawDesc
)

func file_proto_fulcrum_proto_rawDescGZIP() []byte {
	file_proto_fulcrum_proto_rawDescOnce.Do(func() {
		file_proto_fulcrum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fulcrum_proto_rawDescData)
	})
	return file_proto_fulcrum_proto_rawDescData
}

var file_proto_fulcrum_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_fulcrum_proto_goTypes = []interface{}{
	(*AgregarBaseRequest)(nil),      // 0: fulcrum.AgregarBaseRequest
	(*AgregarBaseResponse)(nil),     // 1: fulcrum.AgregarBaseResponse
	(*RenombrarBaseRequest)(nil),    // 2: fulcrum.RenombrarBaseRequest
	(*RenombrarBaseResponse)(nil),   // 3: fulcrum.RenombrarBaseResponse
	(*ActualizarValorRequest)(nil),  // 4: fulcrum.ActualizarValorRequest
	(*ActualizarValorResponse)(nil), // 5: fulcrum.ActualizarValorResponse
	(*BorrarBaseRequest)(nil),       // 6: fulcrum.BorrarBaseRequest
	(*BorrarBaseResponse)(nil),      // 7: fulcrum.BorrarBaseResponse
	(*GetEnemigosRequest)(nil),      // 8: fulcrum.GetEnemigosRequest
	(*GetEnemigosResponse)(nil),     // 9: fulcrum.GetEnemigosResponse
}
var file_proto_fulcrum_proto_depIdxs = []int32{
	0, // 0: fulcrum.Fulcrum.AgregarBase:input_type -> fulcrum.AgregarBaseRequest
	2, // 1: fulcrum.Fulcrum.RenombrarBase:input_type -> fulcrum.RenombrarBaseRequest
	4, // 2: fulcrum.Fulcrum.ActualizarValor:input_type -> fulcrum.ActualizarValorRequest
	6, // 3: fulcrum.Fulcrum.BorrarBase:input_type -> fulcrum.BorrarBaseRequest
	8, // 4: fulcrum.Fulcrum.GetEnemigos:input_type -> fulcrum.GetEnemigosRequest
	1, // 5: fulcrum.Fulcrum.AgregarBase:output_type -> fulcrum.AgregarBaseResponse
	3, // 6: fulcrum.Fulcrum.RenombrarBase:output_type -> fulcrum.RenombrarBaseResponse
	5, // 7: fulcrum.Fulcrum.ActualizarValor:output_type -> fulcrum.ActualizarValorResponse
	7, // 8: fulcrum.Fulcrum.BorrarBase:output_type -> fulcrum.BorrarBaseResponse
	9, // 9: fulcrum.Fulcrum.GetEnemigos:output_type -> fulcrum.GetEnemigosResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fulcrum_proto_init() }
func file_proto_fulcrum_proto_init() {
	if File_proto_fulcrum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fulcrum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgregarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgregarBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenombrarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenombrarBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizarValorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActualizarValorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrarBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrarBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnemigosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fulcrum_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnemigosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fulcrum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fulcrum_proto_goTypes,
		DependencyIndexes: file_proto_fulcrum_proto_depIdxs,
		MessageInfos:      file_proto_fulcrum_proto_msgTypes,
	}.Build()
	File_proto_fulcrum_proto = out.File
	file_proto_fulcrum_proto_rawDesc = nil
	file_proto_fulcrum_proto_goTypes = nil
	file_proto_fulcrum_proto_depIdxs = nil
}
